services:
  redis:
    image: redis:8
    container_name: redis
    ports:
      - "6379:6379"

  python-api:
    build: ./processing
    container_name: python-api
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BACKEND_CALLBACK_URL=http://host.docker.internal:5243/jobs
    depends_on:
      - redis

  worker:
    build: ./processing
    command: rq worker --url redis://redis:6379 default
    depends_on:
      - redis
    volumes:
      - ./backend/storage/images:/app/images
